# 应用名称
spring:
  application:
    name: text
    admin:
      enabled: false
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: Jt123456.
      filter:
        stat:
          enabled: true
#          慢sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true

server:
  port: 9999
  servlet:
    context-path: /ak47
logging:
  level:
    com.jt.test.mapper : debug

