# 应用名称
spring:
  application:
    name: text
    admin:
      enabled: false
# springfox使用的路径匹配是基于ant_path_matcher,spring-boot 2.6.x之后使用的是path_pattern_matcher(parser),不更改knife4j会白页错误
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: Jt123456.
      filter:
        stat:
          enabled: true
#          慢sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true

server:
  port: 80
#  servlet:
#    context-path: /ak47
logging:
  level:
    com.jt.test.mapper : debug

wechat:
  mpAppId: wxf9fc4558c1f2812e
  mpAppSecret: bbb816109367824cf2f96bae0e791100
  mpToken: 678911

