server:
  port: 8088
#  servlet:
#    context-path: /ak47
# 应用名称
spring:
  application:
    name: testHub
    admin:
      enabled: false
# springfox使用的路径匹配是基于ant_path_matcher,spring-boot 2.6.x之后使用的是path_pattern_matcher(parser),不更改knife4j会白页错误
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  生产环境：
#  spring.redis.lettuce.pool.max-active = 大于cpu*2
#  spring.redis.lettuce.pool.max-idle = cpu*2
#  spring.redis.lettuce.pool.max-wait = 5s
#  spring.redis.lettuce.pool.min-idle = 0
#  spring.redis.lettuce.pool.time-between-eviction-runs = 1s
#  如果以@Configuration配置了redis连接，这里则不会读取
  redis:
    database: 3
    host: 192.168.1.198
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 24
        max-active: 30
        max-wait: 5s

  datasource:
    druid:
      url: jdbc:mysql://192.168.1.198:3306/mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: Jt123456.
      filter:
        stat:
          enabled: true
#          慢sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
  mail:
    host: smtp.qq.com #smtp服务器地址
    username: 510791331@qq.com
    password: eqwavaphcxcebjbe #生成的授权码
    default-encoding: utf-8
  elasticsearch:
    rest:
#      enable: ture
      host: 192.168.186.128
      port: 9200
  banner:
    image:
      width: 50
      height: 25
      bitdepth: 4
# mybatis
mybatis-plus:
  type-aliases-package: com.jt.test.demo1.domain.entity
  # 指定mybatis映射文件的位置
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  configuration:
    # 开启驼峰命名转换（开启后需要注意字段写法，不然返回值为null）
    map-underscore-to-camel-case: true
    # 替换log实现类
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: AUTO
#打印sql
logging:
  level:
    com.jt.test.demo1.mapper: debug

wechat:
  #正式的
  #  mpAppId: wxbaf2ce65862f52a8
  #测试号
  mpAppId: wxf9fc4558c1f2812e
  #  mpAppSecret: 5c3bf830eb7ddb3c7383ebc81e6e55c4
  #测试号
  mpAppSecret: bbb816109367824cf2f96bae0e791100
  mpToken: 678911
  test: hh

#个人设置
jt:
  mqtt:
    SERVER_URI: tcp://127.0.0.1:1883
    CLIENT_ID: ""
    USER_NAME: ""
    PASS_WORD: ""
    topic: /jqtt/test
    statusTopic: /jqtt/ssss
    test_ip: 192.168.1.168
